#!/usr/bin/env bash
#script displaying  Best School with 9th iteration of Hi
n=1
while [ "$n" -lt 10 ]
do
	
	if [ "$n" = 9 ];
	then
		echo "Hi"
		
		echo "Best School"
	else
		echo "Best School"
	fi

	((n++))
done
