#!/usr/bin/env bash
#bash script displaying 1-20
#displays 4 then badluck from china on 4th loop iteration
#displays 9 then bad luck from japan on the 9th loop iteration
n=1
while [ "$n" -le 20 ];
do
	case "$n" in
		4 )
			echo "$n"
			echo "bad luck from China"
			;;
		9 )
			echo "$n"
			echo "bad luck from Japan"
			;;
		17 )
			echo "$n"
			echo "bad luck from Italy"
			;;
		* )
			echo "$n"
			;;
	esac
	((n++))
done
