#!/usr/bin/env bash
#bash script displaying ttime for 12 hrs  59 minutes
Hour=0
while [ $Hour -le 12 ]
do
	echo "Hour: $Hour"
		Minute=1
		while [ $Minute -le 60 ]
		do
			echo "$Minute"
		((Minute++))
		done
	((Hour++))
done
