#!/usr/bin/env bash
#bash script that gives info about school use if and else
File="school"
#check if file exists
if [ -e "$File" ]
then
	echo "$File file exists"
	#file not empty
	if [ -s "$File" ]
	then
		echo "$File file is not empty"
	else
		echo "$File file is empty"
	fi
	#regular file
	if [ -f "$File" ]
	then
		echo "$File is a regular file"
	fi
else
	#empty file
	echo "$File file does not exist"
fi
